easy_admin:
    site_name: 'OpinionEat'
    list:
        actions:
            - { name: 'delete', icon: 'times', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
    entities:
        Utilisateur:
            class: App\Entity\User
        Restaurant:
            class: App\Entity\Restaurant
        Avis:
            class: App\Entity\Review
        Category:
            class: App\Entity\Category
            list:
                fields: ['id', 'name']
            form:
                fields: ['name']