framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    session:
        handler_id: ~
    #esi: ~
    #fragments: ~
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    php_errors:
        log: true
