framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    session:
        handler_id: ~
    #esi: ~
    #fragments: ~
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    php_errors:
        log: true