security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_provider:
            entity:
                class: App\Entity\User

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            anonymous: ~
            #guard:
            #    authenticators:
            #        - App\Security\ApiTokenAuthenticator
        main:
            pattern:   ^/
            anonymous: ~
            provider:  app_provider
            logout:
                path:   /logout
                target: /login
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator


            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,      roles: ROLE_USER }
        - { path: ^/admin,    roles: ROLE_ADMIN }